import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import { ClerkProvider } from "@clerk/nextjs";
import { ThemeProvider } from "@/contexts/ThemeContext";
import NavBar from "@/components/NavBar";

const geistSans = Geist({ variable: "--font-geist-sans", subsets: ["latin"] });

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Expense Tracker",
  description: "Generated by create next app",
  // icons: {
  //   icon: "/favicon.ico",
  //   shortcut: "/favicon-16x16.png",
  //   apple: "/apple-touch-icon.png",
  // },
};

const appearance = {
  cssLayerName: "clerk",
  variables: {
    colorBackground: "var(--color-neutral)",
    colorPrimary: "var(--color-primary)",
    colorForeground: "var(--color-neutral-content)",
    colorPrimaryForeground: "var(--color-primary-content)",
    colorText: "var(--color-neutral-content)",
    colorTextSecondary: "var(--color-neutral-content)",
    colorBorder: "var(--color-neutral-content)",
    colorInput: "var(--color-neutral)",
    colorInputBackground: "var(--color-neutral)",
    colorInputText: "var(--color-neutral-content)",
    colorInputForeground: "var(--color-neutral-content)",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ThemeProvider>
      <ClerkProvider
        appearance={{
          cssLayerName: "clerk",
          variables: {
            colorBackground: "var(--color-neutral)",
            colorPrimary: "var(--color-primary)",
            colorForeground: "var(--color-neutral-content)",
            colorPrimaryForeground: "var(--color-primary-content)",
            colorText: "var(--color-neutral-content)",
            colorTextSecondary: "var(--color-neutral-content)",
            colorBorder: "var(--color-neutral-content)",
            colorInput: "var(--color-neutral)",
            colorInputBackground: "var(--color-neutral)",
            colorInputText: "var(--color-neutral-content)",
            colorInputForeground: "var(--color-neutral-content)",
            colorNeutral: "var(--color-base-content)",
          },
        }}
      >
        <html lang="en">
          <body
            className={`${geistSans.variable} ${geistMono.variable} antialiased`}
          >
            <NavBar />
            <main className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
              {children}
            </main>
          </body>
        </html>
      </ClerkProvider>
    </ThemeProvider>
  );
}
